### ISSUE TITLE
Python 3.9.0 运行报错如下

### ISSUE THREAD

**Issue by ChenRuihua** [Abeautifulsnow/navicat-premium-crack#1]
运行提示错误如下：
```
D:\>python crack_navicat_win.py
Start to delete registry...
Traceback (most recent call last):
  File "D:\crack_navicat_win.py", line 21, in get_sub_keys
    sub_keys = winreg.EnumKey(key_result, i)
OSError: [WinError 259] 没有可用的数据了。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\crack_navicat_win.py", line 68, in <module>
    main()
  File "D:\crack_navicat_win.py", line 52, in main
    clsid_all_keys_list = get_all_keys(HKEY_CURRENT_USER, CLSID_PATH)
  File "D:\crack_navicat_win.py", line 39, in get_all_keys
    for item in get_sub_keys(root, sub_key_path):
  File "D:\crack_navicat_win.py", line 24, in get_sub_keys
    except expression:
NameError: name 'expression' is not defined
```

**Comment by Abeautifulsnow** [comment]
`OSError: [WinError 259] 没有可用的数据了。`这个错误是因为那个最下面的错误`NameError: name 'expression' is not defined`间接导致而显示出来的，是我敲错了单词`Exception`😑，已修复，非常感谢😁。至于真正的错误原因可能是下面两个路径
```python3
PREMIUM_PATH = r'Software\PremiumSoft'
CLSID_PATH = r'Software\Classes\CLSID'
```
下面并没有什么内容，也就是代表这俩路径下面已经是没有代码中设定的需要清除的数据。
因为此处错误提示是因为`sub_keys = winreg.EnumKey(key_result, i)`引起的：
```powershell
OSError: [WinError 259] No more data is available
        if the index is out of Range
```

`winreg.EnumKey`的使用：
```powershell
EnumKey(key, index, /)
    Enumerates subkeys of an open registry key.

      key
        An already open key, or any one of the predefined HKEY_* constants.
      index
        An integer that identifies the index of the key to retrieve.

    The function retrieves the name of one subkey each time it is called.
    It is typically called repeatedly until an OSError exception is
    raised, indicating no more values are available.
```
所以可能是因为你已经删除过了，所以上面的两个路径下就已经没有navicat的注册表信息了。

**Comment by ChenRuihua** [comment]
已经可以了。谢谢。
